# Generated by Django 5.2.7 on 2025-10-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_doc_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на документ'),
        ),
    ]
