# Generated by Django 5.2.7 on 2025-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_example',
            field=models.URLField(blank=True, default='', verbose_name='Примеры резюме'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.URLField(blank=True, default='', verbose_name='Моё резюме'),
        ),
    ]
