# Generated by Django 5.2.7 on 2025-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_resume_example_profile_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на задание'),
        ),
    ]
