# Generated by Django 5.2.7 on 2026-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calc_url',
            field=models.URLField(blank=True, default='', verbose_name="Ссылка на практическую работа по теме 'Калькулятор'"),
        ),
    ]
