# Generated by Django 5.2.7 on 2026-02-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_calc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='robot_url',
            field=models.URLField(blank=True, default='', verbose_name="Ссылка на практическую работа по теме 'Среда программирования'"),
        ),
    ]
