# Generated by Django 5.2.7 on 2026-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_robot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info_search_url',
            field=models.URLField(blank=True, default='', verbose_name="Ссылка на задание 'Поиск информации'"),
        ),
    ]
