# Generated by Django 5.2.7 on 2025-11-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_created_by'),
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by', to='trade.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SELL_REVENUE', 'Seller revenue')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'SELL_REVENUE')), fields=('type', 'original_tx'), name='uniq_seller_revenue_per_buy'),
        ),
    ]
