# Generated by Django 5.2.7 on 2025-10-19 17:03

import catalog.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('next_change_at', models.DateTimeField(default=catalog.models.default_next_change)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
