# Generated by Django 5.2.7 on 2025-10-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'permissions': [('can_tick_prices', 'Can run price tick for products')]},
        ),
    ]
