# Generated by Django 5.2.7 on 2025-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_last_edited_at_product_last_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
